### PR TITLE
fix(FEC-12717): add timeline dependency to ima-dai plugin

### PR DESCRIPTION
**Pull request by amirch1**
### Description of the Changes

Please add a detailed description of the change, whether it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

### CODE REVIEW

**Comment by SivanA-Kaltura** [comment]
hi @amirch1 
which branch is this merged into ? not sure what kaltura:master is.
also, if this change should be included as part of our release the pr name / commit prefix should probably be "fix(FEC-12717):".

**Comment by SivanA-Kaltura** [comment]
@amirch1 thanks

**Review by SivanA-Kaltura — APPROVED** [review]

**Review by giladna — APPROVED** [review]

**Review by SivanA-Kaltura — CHANGES_REQUESTED** [review]
@amirch1 please see my comment here
https://github.com/kaltura/playkit-js-ima/pull/236#pullrequestreview-1178232444

**Review by SivanA-Kaltura — APPROVED** [review]

**Review by SivanA-Kaltura — CHANGES_REQUESTED** [review]
@amirch1 @giladna we need to discuss this PR

**Pull request merged**
